/**
 * this will no longer be needed in the next 13 with app dir
 */
import Head from 'next/head'

type IProps = { title?: string }
export const HtmlHead = ({ title }: IProps) => {
  title = !title ? 'Demo NextJS' : `${title} | Demo NextJS`

  return (
    <Head>
      <title>{title ?? 'Demo NextJS'}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export function setHtmlHead({ title }: IProps) {
  return <HtmlHead title={title} />
}
